import { getCountryCodeByName } from 'country-currency-map';

// Manual mapping for cities and countries to currency codes
const CITY_TO_COUNTRY_CURRENCY = {
  // Major cities with specific currency mappings
  'london': 'GBP',
  'paris': 'EUR',
  'tokyo': 'JPY',
  'new york': 'USD',
  'singapore': 'SGD',
  'sydney': 'AUD',
  'toronto': 'CAD',
  'mumbai': 'INR',
  'delhi': 'INR',
  'bangalore': 'INR',
  'chennai': 'INR',
  'kolkata': 'INR',
  'hyderabad': 'INR',
  'pune': 'INR',
  'ahmedabad': 'INR',
  'jaipur': 'INR',
  'dubai': 'AED',
  'abu dhabi': 'AED',
  'sharjah': 'AED',
  'doha': 'QAR',
  'riyadh': 'SAR',
  'jeddah': 'SAR',
  'mecca': 'SAR',
  'medina': 'SAR',
  'dammam': 'SAR',
  'kuwait city': 'KWD',
  'manama': 'BHD',
  'muscat': 'OMR',
  'beijing': 'CNY',
  'shanghai': 'CNY',
  'guangzhou': 'CNY',
  'shenzhen': 'CNY',
  'hong kong': 'HKD',
  'macau': 'HKD',
  'seoul': 'KRW',
  'busan': 'KRW',
  'bangkok': 'THB',
  'phuket': 'THB',
  'chiang mai': 'THB',
  'kuala lumpur': 'MYR',
  'penang': 'MYR',
  'jakarta': 'IDR',
  'bali': 'IDR',
  'manila': 'PHP',
  'cebu': 'PHP',
  'ho chi minh city': 'VND',
  'hanoi': 'VND',
  'phnom penh': 'KHR',
  'yangon': 'MMK',
  'dhaka': 'BDT',
  'karachi': 'PKR',
  'lahore': 'PKR',
  'islamabad': 'PKR',
  'rawalpindi': 'PKR',
  'faisalabad': 'PKR',
  'multan': 'PKR',
  'peshawar': 'PKR',
  'quetta': 'PKR',
  'sialkot': 'PKR',
  'gujranwala': 'PKR',
  'cairo': 'EGP',
  'alexandria': 'EGP',
  'casablanca': 'MAD',
  'marrakech': 'MAD',
  'tunis': 'TND',
  'algiers': 'DZD',
  'lagos': 'NGN',
  'abuja': 'NGN',
  'nairobi': 'KES',
  'cape town': 'ZAR',
  'johannesburg': 'ZAR',
  'durban': 'ZAR',
  'istanbul': 'TRY',
  'ankara': 'TRY',
  'antalya': 'TRY',
  'moscow': 'RUB',
  'st petersburg': 'RUB',
  'berlin': 'EUR',
  'munich': 'EUR',
  'frankfurt': 'EUR',
  'hamburg': 'EUR',
  'cologne': 'EUR',
  'madrid': 'EUR',
  'barcelona': 'EUR',
  'valencia': 'EUR',
  'seville': 'EUR',
  'rome': 'EUR',
  'milan': 'EUR',
  'venice': 'EUR',
  'florence': 'EUR',
  'naples': 'EUR',
  'amsterdam': 'EUR',
  'rotterdam': 'EUR',
  'the hague': 'EUR',
  'brussels': 'EUR',
  'antwerp': 'EUR',
  'vienna': 'EUR',
  'salzburg': 'EUR',
  'zurich': 'CHF',
  'geneva': 'CHF',
  'basel': 'CHF',
  'bern': 'CHF',
  'stockholm': 'SEK',
  'gothenburg': 'SEK',
  'oslo': 'NOK',
  'bergen': 'NOK',
  'copenhagen': 'DKK',
  'aarhus': 'DKK',
  'helsinki': 'EUR',
  'tampere': 'EUR',
  'reykjavik': 'ISK',
  'dublin': 'EUR',
  'cork': 'EUR',
  'edinburgh': 'GBP',
  'glasgow': 'GBP',
  'manchester': 'GBP',
  'birmingham': 'GBP',
  'liverpool': 'GBP',
  'leeds': 'GBP',
  'bristol': 'GBP',
  'cardiff': 'GBP',
  'belfast': 'GBP',
  'warsaw': 'PLN',
  'krakow': 'PLN',
  'gdansk': 'PLN',
  'prague': 'CZK',
  'brno': 'CZK',
  'budapest': 'HUF',
  'debrecen': 'HUF',
  'bucharest': 'RON',
  'cluj-napoca': 'RON',
  'sofia': 'BGN',
  'plovdiv': 'BGN',
  'zagreb': 'HRK',
  'split': 'HRK',
  'ljubljana': 'EUR',
  'maribor': 'EUR',
  'athens': 'EUR',
  'thessaloniki': 'EUR',
  'lisbon': 'EUR',
  'porto': 'EUR',
  'montreal': 'CAD',
  'vancouver': 'CAD',
  'calgary': 'CAD',
  'ottawa': 'CAD',
  'edmonton': 'CAD',
  'winnipeg': 'CAD',
  'los angeles': 'USD',
  'chicago': 'USD',
  'houston': 'USD',
  'phoenix': 'USD',
  'philadelphia': 'USD',
  'san antonio': 'USD',
  'san diego': 'USD',
  'dallas': 'USD',
  'san jose': 'USD',
  'austin': 'USD',
  'jacksonville': 'USD',
  'fort worth': 'USD',
  'columbus': 'USD',
  'charlotte': 'USD',
  'san francisco': 'USD',
  'indianapolis': 'USD',
  'seattle': 'USD',
  'denver': 'USD',
  'washington': 'USD',
  'boston': 'USD',
  'el paso': 'USD',
  'detroit': 'USD',
  'nashville': 'USD',
  'portland': 'USD',
  'memphis': 'USD',
  'oklahoma city': 'USD',
  'las vegas': 'USD',
  'louisville': 'USD',
  'baltimore': 'USD',
  'milwaukee': 'USD',
  'albuquerque': 'USD',
  'tucson': 'USD',
  'fresno': 'USD',
  'sacramento': 'USD',
  'mesa': 'USD',
  'kansas city': 'USD',
  'atlanta': 'USD',
  'omaha': 'USD',
  'colorado springs': 'USD',
  'raleigh': 'USD',
  'miami': 'USD',
  'oakland': 'USD',
  'minneapolis': 'USD',
  'tulsa': 'USD',
  'cleveland': 'USD',
  'wichita': 'USD',
  'arlington': 'USD',
  'mexico city': 'MXN',
  'guadalajara': 'MXN',
  'monterrey': 'MXN',
  'puebla': 'MXN',
  'tijuana': 'MXN',
  'león': 'MXN',
  'juárez': 'MXN',
  'zapopan': 'MXN',
  'río de janeiro': 'BRL',
  'são paulo': 'BRL',
  'salvador': 'BRL',
  'brasília': 'BRL',
  'fortaleza': 'BRL',
  'belo horizonte': 'BRL',
  'manaus': 'BRL',
  'curitiba': 'BRL',
  'recife': 'BRL',
  'porto alegre': 'BRL',
  'belém': 'BRL',
  'goiânia': 'BRL',
  'buenos aires': 'ARS',
  'córdoba': 'ARS',
  'rosario': 'ARS',
  'mendoza': 'ARS',
  'san miguel de tucumán': 'ARS',
  'la plata': 'ARS',
  'mar del plata': 'ARS',
  'santiago': 'CLP',
  'valparaíso': 'CLP',
  'antofagasta': 'CLP',
  'viña del mar': 'CLP',
  'talcahuano': 'CLP',
  'san bernardo': 'CLP',
  'temuco': 'CLP',
  'iquique': 'CLP',
  'rancagua': 'CLP',
  'talca': 'CLP',
  'arica': 'CLP',
  'chillán': 'CLP',
  'bogotá': 'COP',
  'medellín': 'COP',
  'cali': 'COP',
  'barranquilla': 'COP',
  'cartagena': 'COP',
  'cúcuta': 'COP',
  'soledad': 'COP',
  'ibagué': 'COP',
  'bucaramanga': 'COP',
  'soacha': 'COP',
  'melbourne': 'AUD',
  'brisbane': 'AUD',
  'perth': 'AUD',
  'adelaide': 'AUD',
  'gold coast': 'AUD',
  'newcastle': 'AUD',
  'canberra': 'AUD',
  'sunshine coast': 'AUD',
  'wollongong': 'AUD',
  'hobart': 'AUD',
  'geelong': 'AUD',
  'townsville': 'AUD',
  'cairns': 'AUD',
  'darwin': 'AUD',
  'toowoomba': 'AUD',
  'ballarat': 'AUD',
  'bendigo': 'AUD',
  'auckland': 'NZD',
  'wellington': 'NZD',
  'christchurch': 'NZD',
  'hamilton': 'NZD',
  'tauranga': 'NZD',
  'napier-hastings': 'NZD',
  'dunedin': 'NZD',
  'palmerston north': 'NZD',
  'nelson': 'NZD',
  'rotorua': 'NZD',
  'new plymouth': 'NZD',
  'whangarei': 'NZD',
  'invercargill': 'NZD',
  'whanganui': 'NZD',
  'gisborne': 'NZD',
};

// Manual mapping for countries to currency codes (fallback)
const COUNTRY_TO_CURRENCY = {
  'united kingdom': 'GBP',
  'uk': 'GBP',
  'england': 'GBP',
  'scotland': 'GBP',
  'wales': 'GBP',
  'northern ireland': 'GBP',
  'united states': 'USD',
  'usa': 'USD',
  'america': 'USD',
  'france': 'EUR',
  'germany': 'EUR',
  'italy': 'EUR',
  'spain': 'EUR',
  'netherlands': 'EUR',
  'belgium': 'EUR',
  'austria': 'EUR',
  'finland': 'EUR',
  'ireland': 'EUR',
  'portugal': 'EUR',
  'greece': 'EUR',
  'slovenia': 'EUR',
  'slovakia': 'EUR',
  'estonia': 'EUR',
  'latvia': 'EUR',
  'lithuania': 'EUR',
  'malta': 'EUR',
  'cyprus': 'EUR',
  'luxembourg': 'EUR',
  'japan': 'JPY',
  'china': 'CNY',
  'india': 'INR',
  'singapore': 'SGD',
  'australia': 'AUD',
  'canada': 'CAD',
  'switzerland': 'CHF',
  'hong kong': 'HKD',
  'new zealand': 'NZD',
  'sweden': 'SEK',
  'south korea': 'KRW',
  'korea': 'KRW',
  'norway': 'NOK',
  'mexico': 'MXN',
  'russia': 'RUB',
  'south africa': 'ZAF',
  'turkey': 'TRY',
  'brazil': 'BRL',
  'taiwan': 'TWD',
  'denmark': 'DKK',
  'poland': 'PLN',
  'thailand': 'THB',
  'indonesia': 'IDR',
  'hungary': 'HUF',
  'czech republic': 'CZK',
  'israel': 'ILS',
  'chile': 'CLP',
  'philippines': 'PHP',
  'united arab emirates': 'AED',
  'uae': 'AED',
  'emirates': 'AED',
  'colombia': 'COP',
  'saudi arabia': 'SAR',
  'malaysia': 'MYR',
  'romania': 'RON',
  'peru': 'PEN',
  'pakistan': 'PKR',
  'bulgaria': 'BGN',
  'nigeria': 'NGN',
  'bangladesh': 'BDT',
  'vietnam': 'VND',
  'ukraine': 'UAH',
  'egypt': 'EGP',
  'morocco': 'MAD',
  'kenya': 'KES',
  'iraq': 'IQD',
  'qatar': 'QAR',
  'kuwait': 'KWD',
  'algeria': 'DZD',
  'oman': 'OMR',
  'jordan': 'JOD',
  'bahrain': 'BHD',
  'tunisia': 'TND',
  'ghana': 'GHS',
  'uganda': 'UGX',
  'tanzania': 'TZS',
  'ethiopia': 'ETB',
  'costa rica': 'CRC',
  'argentina': 'ARS',
  'bolivia': 'BOB',
  'uruguay': 'UYU',
  'paraguay': 'PYG',
  'jamaica': 'JMD',
  'trinidad and tobago': 'TTD',
  'kazakhstan': 'KZT',
  'uzbekistan': 'UZS',
  'turkmenistan': 'TMT',
  'armenia': 'AMD',
  'georgia': 'GEL',
  'afghanistan': 'AFN',
  'nepal': 'NPR',
  'sri lanka': 'LKR',
  'myanmar': 'MMK',
  'mongolia': 'MNT',
  'cambodia': 'KHR',
  'laos': 'LAK',
  'fiji': 'FJD',
  'vanuatu': 'VUV',
  'samoa': 'WST',
  'tonga': 'TOP',
  'solomon islands': 'SBD',
  'iceland': 'ISK',
  'belarus': 'BYN',
  'mauritius': 'MUR',
  'moldova': 'MDL',
  'north macedonia': 'MKD',
  'azerbaijan': 'AZN',
  'bosnia and herzegovina': 'BAM',
  'albania': 'ALL',
  'croatia': 'HRK',
  'serbia': 'RSD'
};

/**
 * Get currency code based on location (city or country name)
 * @param location - The location string (city or country name)
 * @returns Currency code (e.g., 'USD', 'EUR', 'GBP') or 'USD' as fallback
 */
export function getCurrencyByLocation(location: string): string {
  if (!location) return 'USD';
  
  const normalizedLocation = location.toLowerCase().trim();
  
  // First, try to find the currency by city
  if (CITY_TO_COUNTRY_CURRENCY[normalizedLocation]) {
    return CITY_TO_COUNTRY_CURRENCY[normalizedLocation];
  }
  
  // Then, try to find by country
  if (COUNTRY_TO_CURRENCY[normalizedLocation]) {
    return COUNTRY_TO_CURRENCY[normalizedLocation];
  }
  
  // Try to find partial matches for cities
  for (const [city, currency] of Object.entries(CITY_TO_COUNTRY_CURRENCY)) {
    if (normalizedLocation.includes(city) || city.includes(normalizedLocation)) {
      return currency;
    }
  }
  
  // Try to find partial matches for countries
  for (const [country, currency] of Object.entries(COUNTRY_TO_CURRENCY)) {
    if (normalizedLocation.includes(country) || country.includes(normalizedLocation)) {
      return currency;
    }
  }
  
  // Try using the country-currency-map library as fallback
  try {
    const countryCode = getCountryCodeByName(location);
    if (countryCode) {
      // You would need to implement a mapping from country code to currency
      // For now, we'll use our manual mapping
      return 'USD'; // fallback
    }
  } catch (error) {
    console.warn('Could not determine currency from location:', location);
  }
  
  // Default fallback
  return 'USD';
}

/**
 * Extract location from search parameters or session storage
 * @param city - The city parameter from search
 * @param sessionData - Optional session data that might contain location info
 * @returns The location string to use for currency detection
 */
export function extractLocationForCurrency(city?: string, sessionData?: any): string {
  // Try to get city from URL parameters first
  if (city) {
    return city;
  }
  
  // Try to extract from session data
  if (sessionData?.selectedCity?.name) {
    return sessionData.selectedCity.name;
  }
  
  if (sessionData?.search?.city) {
    return sessionData.search.city;
  }
  
  // Fallback
  return 'Mumbai'; // Default city
}
